In [101]:
import pandas as pd
import matplotlib as mpl

In [102]:
data = pd.read_csv("assults.csv")

In [103]:
data

,Index,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
0,1,514102,Auckland Central West,550,15900,346,6.6,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
1,2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
2,3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region
3,4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
4,5,591500,Cathedral Square,305,570,"5,351",102.3,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,2016,506653,Riverhead,0,3510,-,-,502,Rural (Incl.some Off Shore Islands),Rural area,76,Auckland,2,Auckland Region
2016,2017,610601,Grasmere,0,3590,-,-,24,Invercargill,Main urban area,75,Invercargill City,15,Southland Region
2017,2018,536513,Bethlehem East,0,3590,-,-,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
2018,2019,574302,Te Kainga,0,4020,-,-,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
2019,2020,527007,Horsham Downs,0,5440,-,-,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region

#1. Hur många regioner finns med i data?

In [104]:
data["Region_2013_label"].unique()

array(['Auckland Region', 'Wellington Region', 'Waikato Region',
       'Canterbury Region', 'Manawatu-Wanganui Region',
       'Bay of Plenty Region', 'Otago Region', 'Nelson Region',
       "Hawke's Bay Region", 'Gisborne Region', 'Taranaki Region',
       'Marlborough Region', 'Northland Region', 'Southland Region',
       'Tasman Region', 'West Coast Region', 'Area Outside Region'],
      dtype=object)

In [105]:
data["Region_2013_label"].unique().shape[0]

17

#2. Lista regionerna i bokstavsordning

In [106]:
region_sorted_name = data["Region_2013_label"].sort_values().unique()
print("Region is alphabetical order:")
region_sorted_name

Region is alphabetical order:

array(['Area Outside Region', 'Auckland Region', 'Bay of Plenty Region',
       'Canterbury Region', 'Gisborne Region', "Hawke's Bay Region",
       'Manawatu-Wanganui Region', 'Marlborough Region', 'Nelson Region',
       'Northland Region', 'Otago Region', 'Southland Region',
       'Taranaki Region', 'Tasman Region', 'Waikato Region',
       'Wellington Region', 'West Coast Region'], dtype=object)

#3. Vad är invånarantalet i varje region

In [107]:
data[["Population_mid_point_2015","Region_2013_label"]]

      Population_mid_point_2015     Region_2013_label
0                         15900       Auckland Region
1                          8300     Wellington Region
2                          3170        Waikato Region
3                         13250       Auckland Region
4                           570     Canterbury Region
...                         ...                   ...
2015                       3510       Auckland Region
2016                       3590      Southland Region
2017                       3590  Bay of Plenty Region
2018                       4020     Wellington Region
2019                       5440        Waikato Region

[2020 rows x 2 columns]

In [108]:
resulted_population_region = data[["Population_mid_point_2015","Region_2013_label"]]
resulted_population_region

      Population_mid_point_2015     Region_2013_label
0                         15900       Auckland Region
1                          8300     Wellington Region
2                          3170        Waikato Region
3                         13250       Auckland Region
4                           570     Canterbury Region
...                         ...                   ...
2015                       3510       Auckland Region
2016                       3590      Southland Region
2017                       3590  Bay of Plenty Region
2018                       4020     Wellington Region
2019                       5440        Waikato Region

[2020 rows x 2 columns]

In [109]:
resulted_population_region.groupby('Region_2013_label').sum()

                          Population_mid_point_2015
Region_2013_label
Area Outside Region                             610
Auckland Region                             1569890
Bay of Plenty Region                         287130
Canterbury Region                            586310
Gisborne Region                               47370
Hawke's Bay Region                           160010
Manawatu-Wanganui Region                     234460
Marlborough Region                            45340
Nelson Region                                 49940
Northland Region                             168320
Otago Region                                 215030
Southland Region                              97190
Taranaki Region                              115760
Tasman Region                                 49500
Waikato Region                               439000
Wellington Region                            496890
West Coast Region                             32700

#4. Hur många brott begicks i varje region

In [110]:
data[["Victimisations_calendar_year_2015","Region_2013_label"]]

      Victimisations_calendar_year_2015     Region_2013_label
0                                   550       Auckland Region
1                                   447     Wellington Region
2                                   380        Waikato Region
3                                   375       Auckland Region
4                                   305     Canterbury Region
...                                 ...                   ...
2015                                  0       Auckland Region
2016                                  0      Southland Region
2017                                  0  Bay of Plenty Region
2018                                  0     Wellington Region
2019                                  0        Waikato Region

[2020 rows x 2 columns]

In [111]:
victim = data[["Victimisations_calendar_year_2015","Region_2013_label"]]

In [112]:
victim

      Victimisations_calendar_year_2015     Region_2013_label
0                                   550       Auckland Region
1                                   447     Wellington Region
2                                   380        Waikato Region
3                                   375       Auckland Region
4                                   305     Canterbury Region
...                                 ...                   ...
2015                                  0       Auckland Region
2016                                  0      Southland Region
2017                                  0  Bay of Plenty Region
2018                                  0     Wellington Region
2019                                  0        Waikato Region

[2020 rows x 2 columns]

In [113]:
victim.groupby('Region_2013_label').sum()

                          Victimisations_calendar_year_2015
Region_2013_label
Area Outside Region                                       0
Auckland Region                                        8010
Bay of Plenty Region                                   1751
Canterbury Region                                      2942
Gisborne Region                                         436
Hawke's Bay Region                                     1068
Manawatu-Wanganui Region                               1270
Marlborough Region                                      209
Nelson Region                                           357
Northland Region                                        905
Otago Region                                           1142
Southland Region                                        381
Taranaki Region                                         493
Tasman Region                                           161
Waikato Region                                         2330
Wellington Region                                      2459
West Coast Region                                       121

#5. Skapa en dataframe på de områden med de 10 högsta antalet överfall.

In [114]:
data[["Victimisations_calendar_year_2015","Area_unit_2013_label"]]

      Victimisations_calendar_year_2015             Area_unit_2013_label
0                                   550            Auckland Central West
1                                   447  Willis Street-Cambridge Terrace
2                                   380                 Hamilton Central
3                                   375            Auckland Central East
4                                   305                 Cathedral Square
...                                 ...                              ...
2015                                  0                        Riverhead
2016                                  0                         Grasmere
2017                                  0                   Bethlehem East
2018                                  0                        Te Kainga
2019                                  0                    Horsham Downs

[2020 rows x 2 columns]

In [115]:
highest_10_area = data[["Victimisations_calendar_year_2015","Area_unit_2013_label"]]
highest_10_area

      Victimisations_calendar_year_2015             Area_unit_2013_label
0                                   550            Auckland Central West
1                                   447  Willis Street-Cambridge Terrace
2                                   380                 Hamilton Central
3                                   375            Auckland Central East
4                                   305                 Cathedral Square
...                                 ...                              ...
2015                                  0                        Riverhead
2016                                  0                         Grasmere
2017                                  0                   Bethlehem East
2018                                  0                        Te Kainga
2019                                  0                    Horsham Downs

[2020 rows x 2 columns]

In [116]:
highest_10_area.groupby('Area_unit_2013_label').count()

                      Victimisations_calendar_year_2015
Area_unit_2013_label
Abbey Caves                                           1
Abbotsford                                            1
Abbotts Park                                          1
Acacia Bay                                            1
Addington                                             1
...                                                 ...
Wyllies Crossing                                      1
Wymondley                                             1
Wyndham                                               1
Yaldhurst                                             1
Yatton Park                                           1

[2020 rows x 1 columns]

In [117]:
 highest_10_area= data[['Area_unit_2013_label','Victimisations_calendar_year_2015']]
orderd_no_of_assult = highest_10_area.sort_values(['Victimisations_calendar_year_2015'], ascending = [False])
result = orderd_no_of_assult.iloc[:10]

In [118]:
result

              Area_unit_2013_label  Victimisations_calendar_year_2015
0            Auckland Central West                                550
1  Willis Street-Cambridge Terrace                                447
2                 Hamilton Central                                380
3            Auckland Central East                                375
4                 Cathedral Square                                305
5             Auckland Harbourside                                253
6                  Manukau Central                                192
7         Palmerston North Central                                190
8                           Kuirau                                168
9                 Tauranga Central                                167

#6. Lägg till en kolumn i dataframen som visar % antal överfall i området jämfört med
invånarantal i området

In [19]:
Population_of_victimisation = data["Victimisations_calendar_year_2015"]/data["Population_mid_point_2015"]* 100
Population_of_victimisation

0        3.459119
1        5.385542
2       11.987382
3        2.830189
4       53.508772
          ...
2015     0.000000
2016     0.000000
2017     0.000000
2018     0.000000
2019     0.000000
Length: 2020, dtype: float64

In [20]:
Population_of_victimisation

0        3.459119
1        5.385542
2       11.987382
3        2.830189
4       53.508772
          ...
2015     0.000000
2016     0.000000
2017     0.000000
2018     0.000000
2019     0.000000
Length: 2020, dtype: float64

In [21]:
data["Population_of_victimisation"] = Population_of_victimisation.head()

In [22]:
data

,Index,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label,Population_of_victimisation
0,1,514102,Auckland Central West,550,15900,346,6.6,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region,3.459119
1,2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region,5.385542
2,3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region,11.987382
3,4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region,2.830189
4,5,591500,Cathedral Square,305,570,"5,351",102.3,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region,53.508772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,2016,506653,Riverhead,0,3510,-,-,502,Rural (Incl.some Off Shore Islands),Rural area,76,Auckland,2,Auckland Region,NaN
2016,2017,610601,Grasmere,0,3590,-,-,24,Invercargill,Main urban area,75,Invercargill City,15,Southland Region,NaN
2017,2018,536513,Bethlehem East,0,3590,-,-,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region,NaN
2018,2019,574302,Te Kainga,0,4020,-,-,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region,NaN
2019,2020,527007,Horsham Downs,0,5440,-,-,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region,NaN

#7. Skapa en ny dataframe som innehåller antalet områden som finns av de olika typerna av
urban area. Ledtråd: groupby

In [185]:
Selected_area_urban = data [['Urban_area_2013_label','Area_unit_2013_label']]
print(Selected_Urban_area)

                    Urban_area_2013_label             Area_unit_2013_label
0                   Central Auckland Zone            Auckland Central West
1                         Wellington Zone  Willis Street-Cambridge Terrace
2                           Hamilton Zone                 Hamilton Central
3                   Central Auckland Zone            Auckland Central East
4                            Christchurch                 Cathedral Square
...                                   ...                              ...
2015  Rural (Incl.some Off Shore Islands)                        Riverhead
2016                         Invercargill                         Grasmere
2017                             Tauranga                   Bethlehem East
2018                      Wellington Zone                        Te Kainga
2019                        Hamilton Zone                    Horsham Downs

[2020 rows x 2 columns]

In [186]:
#a = Selected_area_urban
#a

                    Urban_area_2013_label             Area_unit_2013_label
0                   Central Auckland Zone            Auckland Central West
1                         Wellington Zone  Willis Street-Cambridge Terrace
2                           Hamilton Zone                 Hamilton Central
3                   Central Auckland Zone            Auckland Central East
4                            Christchurch                 Cathedral Square
...                                   ...                              ...
2015  Rural (Incl.some Off Shore Islands)                        Riverhead
2016                         Invercargill                         Grasmere
2017                             Tauranga                   Bethlehem East
2018                      Wellington Zone                        Te Kainga
2019                        Hamilton Zone                    Horsham Downs

[2020 rows x 2 columns]

In [191]:
a = Selected_area_urban.groupby('Urban_area_2013_label').count()
a

                       Area_unit_2013_label
Urban_area_2013_label
Alexandra                                 1
Amberley                                  1
Arrowtown                                 1
Ashburton                                11
Balclutha                                 1
...                                     ...
Whangarei                                29
Whitianga                                 1
Winton                                    1
Woodend                                   3
Woodville                                 1

[150 rows x 1 columns]

In [23]:
urban_area_counts = data.groupby("Urban_area_2013_label").size().reset_index(name="Count")
print(urban_area_counts)

    Urban_area_2013_label  Count
0               Alexandra      1
1                Amberley      1
2               Arrowtown      1
3               Ashburton     11
4               Balclutha      1
..                    ...    ...
145             Whangarei     29
146             Whitianga      1
147                Winton      1
148               Woodend      3
149             Woodville      1

[150 rows x 2 columns]

#8= Ta reda på hur många områden (varje rad är ett område) hade population men inga överfall. Jämfört totala populationen i dessa med totala populationen i deras region (Region_2013_label).

In [119]:
no_assaults_areas = data[(data["Victimisations_calendar_year_2015"] == 0) & (data["Population_mid_point_2015"] > 0)]
region_population = no_assaults_areas.groupby("Region_2013_label")["Population_mid_point_2015"].sum().reset_index(name="Region_Population")
total_population = no_assaults_areas["Population_mid_point_2015"].sum()

region_population["Population_Difference"] = region_population["Region_Population"] - total_population

print("Number of areas with population but no assaults: ", len(no_assaults_areas))
print(region_population)

Number of areas with population but no assaults:  291
           Region_2013_label  Region_Population  Population_Difference
0        Area Outside Region                610                -212170
1            Auckland Region              32520                -180260
2       Bay of Plenty Region               6380                -206400
3          Canterbury Region              37850                -174930
4            Gisborne Region               1500                -211280
5         Hawke's Bay Region               5360                -207420
6   Manawatu-Wanganui Region               9610                -203170
7         Marlborough Region               2790                -209990
8              Nelson Region               1570                -211210
9           Northland Region               5870                -206910
10              Otago Region              17290                -195490
11          Southland Region              14060                -198720
12           Taranaki Region              13750                -199030
13             Tasman Region               1020                -211760
14            Waikato Region              18780                -194000
15         Wellington Region              36110                -176670
16         West Coast Region               7710                -205070

#9. Räkna per kolumn hur många rader det är som inte innehåller någon data.

In [120]:
null_values = data.isnull().sum()

In [121]:
null_values

Index                                    0
Area_unit_2013_code                      0
Area_unit_2013_label                     0
Victimisations_calendar_year_2015        0
Population_mid_point_2015                0
 Rate_per_10000_population               0
 Rate_ratio_NZ_average_rate              0
Urban_area_2013_code                     0
Urban_area_2013_label                    0
Urban_area_type                          0
Territorial_authority_area_2013_code     0
Territorial_authority_area_2013_label    0
Region_2013_code                         0
Region_2013_label                        0
dtype: int64

#10. Skapa en ny dataframe med 10 rader. Den innehåller de 10 rader med lägsta antalet överfall
per invånare (Rate_per_10000_population), men mer än 5000 invånare.

In [97]:
data.sort_values([ "Victimisations_calendar_year_2015", "Population_mid_point_2015"],ascending=True )

,Index,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label,Population_of_victimisation
1613,1614,619900,White Island,0,0,-,-,502,Rural (Incl.some Off Shore Islands),Rural area,999,Area Outside Territorial Authority,4,Bay of Plenty Region,NaN
1614,1615,617102,Inlet-Kaipara River,0,0,-,-,507,Inlet-in TA but not in Urban Area,Rural area,76,Auckland,2,Auckland Region,NaN
1615,1616,666670,Oceanic-Snares Islands,0,0,-,-,511,Oceanic,Rural area,999,Area Outside Territorial Authority,99,Area Outside Region,NaN
1616,1617,600321,Inland Water-Lake Alexandrina,0,0,-,-,505,Inland Water not in Urban Area,Rural area,65,Mackenzie District,13,Canterbury Region,NaN
1617,1618,619202,Oceanic-Waikato Region West,0,0,-,-,510,Oceanic-in Region but not in TA,Rural area,999,Area Outside Territorial Authority,3,Waikato Region,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,591500,Cathedral Square,305,570,"5,351",102.3,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region,53.508772
3,4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region,2.830189
2,3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region,11.987382
1,2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region,5.385542
0,1,514102,Auckland Central West,550,15900,346,6.6,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region,3.459119

In [127]:
low_assaults = data[(data["Victimisations_calendar_year_2015"]) & (data["Population_mid_point_2015"] > 5000)]
low_assaults

,Index,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
1,2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
3,4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
5,6,514101,Auckland Harbourside,253,5680,445,8.5,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
17,18,522202,Papatoetoe Central,109,5120,213,4.1,5,Southern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
27,28,525910,Pukekohe North,91,9980,91,1.7,101,Pukekohe,Secondary urban area,76,Auckland,2,Auckland Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1235,1236,588500,Bishopdale North,3,5010,6,0.1,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region
1236,1237,508704,Northcross,3,5060,6,0.1,2,Northern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
1237,1238,537000,Matua,3,5440,6,0.1,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
1611,1612,507300,Murrays Bay,1,5150,2,0,2,Northern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
1612,1613,516302,Meadowbank South,1,5560,2,0,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region

In [150]:
lobi= low_assaults.sort_values(["Victimisations_calendar_year_2015"],ascending=[True]).head(10)
print("Top 10 areas with lowest assaults rate per 10000 population but population is more than 5000:")
lobi

Top 10 areas with lowest assaults rate per 10000 population but population is more than 5000:

,Index,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
1612,1613,516302,Meadowbank South,1,5560,2,0,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
1611,1612,507300,Murrays Bay,1,5150,2,0,2,Northern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
1236,1237,508704,Northcross,3,5060,6,0.1,2,Northern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
1237,1238,537000,Matua,3,5440,6,0.1,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
1235,1236,588500,Bishopdale North,3,5010,6,0.1,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region
973,974,537602,Pyes Pa,5,7040,7,0.1,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
972,973,581836,Wai-Iti,5,5660,9,0.2,502,Rural (Incl.some Off Shore Islands),Rural area,51,Tasman District,16,Tasman Region
971,972,522601,Bucklands and Eastern Beaches,5,5620,9,0.2,5,Southern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
970,971,508610,Monarch Park,5,5360,9,0.2,2,Northern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
969,970,518302,Mt Eden South,5,5330,9,0.2,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region

#11. Skapa en ny dataframe ”regions” som innehåller sammansatt data per region
(Region_2013_label). Lägg till en ny kolumn som innehåller ”Rate_per_10000_population”
fast för hela regionen.

In [54]:
regions = data.groupby("Region_2013_label").sum()
regions["Rate_per_10000_population"] = regions["Victimisations_calendar_year_2015"]/regions["Population_mid_point_2015"]* 10000
regions[["Victimisations_calendar_year_2015", "Population_mid_point_2015", "Rate_per_10000_population"]]

,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population
Region_2013_label,,,
Area Outside Region,0,610,0.000000
Auckland Region,8010,1569890,51.022683
Bay of Plenty Region,1751,287130,60.982830
Canterbury Region,2942,586310,50.178233
Gisborne Region,436,47370,92.041376
Hawke's Bay Region,1068,160010,66.745828
Manawatu-Wanganui Region,1270,234460,54.167022
Marlborough Region,209,45340,46.096162
Nelson Region,357,49940,71.485783
Northland Region,905,168320,53.766635
Otago Region,1142,215030,53.108869
Southland Region,381,97190,39.201564
Taranaki Region,493,115760,42.588113
Tasman Region,161,49500,32.525253
Waikato Region,2330,439000,53.075171
Wellington Region,2459,496890,49.487814
West Coast Region,121,32700,37.003058

#12. Lägg till en ny kolumn i dataframen med regionerna som visar i % hur många av alla överfall
som sker i den regionen.

In [55]:
regions["crime_%_per_region"] = regions["Victimisations_calendar_year_2015"]/ regions["Victimisations_calendar_year_2015"].sum()* 100
regions[["Victimisations_calendar_year_2015", "crime_%_per_region"]]

,Victimisations_calendar_year_2015,crime_%_per_region
Region_2013_label,,
Area Outside Region,0,0.000000
Auckland Region,8010,33.326399
Bay of Plenty Region,1751,7.285209
Canterbury Region,2942,12.240483
Gisborne Region,436,1.814021
Hawke's Bay Region,1068,4.443520
Manawatu-Wanganui Region,1270,5.283961
Marlborough Region,209,0.869565
Nelson Region,357,1.485334
Northland Region,905,3.765342
Otago Region,1142,4.751404
Southland Region,381,1.585188
Taranaki Region,493,2.051175
Tasman Region,161,0.669856
Waikato Region,2330,9.694196
Wellington Region,2459,10.230913
West Coast Region,121,0.503432

#Thank You  For Checking My Assignment Again !